services:
  - type: web
    name: neuroscope-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.backend.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /docs
